### ISSUE TITLE
Reparto y documentación a cada miembro

### ISSUE THREAD

**Issue by UO232627** [Arquisoft/dede_es3c#10]

**Comment by UO232627** [comment]
### Sonia
- [ ] 3. System scope and context
- [ ] 6. Runtime View
- [ ] 8.3 Concepts - User interface
- [ ] 10. Quality requirements
- [ ] 12. Glosary

### Nuria
- [ ] 1. Introduction and goals (terminar)
- [ ] 5.2. Building block view - Level 2
- [ ] 8.1 Concepts - Domain model
- [ ] 11. Risks and technical debts
- [ ] 12. Glosary

### Sergio
- [ ] 3. System scope and context
- [ ] 4. Solution strategy
- [ ] 7. Deployment view
- [ ] 8.2 Concepts - Persistency
- [ ] 12. Glosary

### Alejandro
- [ ] 2. Architecture constraints
- [ ] 5.1. Building block view - Level 1
- [ ] 8. Concepts - Mirar que más conceptos vamos a usar
- [ ] 9. Design decisions
- [ ] 12. Glosary

**Comment by NuriaIF** [comment]
> ### Nuria
> * [x]  1. Introduction and goals (terminar)
> * [ ]  5.2. Building block view - Level 2
> * [x]  8.1 Concepts - Domain model
> * [x]  11. Risks and technical debts
> * [x]  12. Glosary

EL 5.2 (Building block view - Level 2) no se ha realizado porque aún no sabemos a ese nivel de detalle los bloques que tendrá nuestra aplicación, por lo que para esta primera entrega solo se ha hecho el Level 1, posponiendo el Level 2 para la próxima entrega.
