### ISSUE TITLE
Leer artículo de Labra sobre SOLID

### ISSUE THREAD

**Issue by SoniaFernandezCoto** [Arquisoft/dede_es3c#12]
Leer el articulo enviado por labra:  https://www.datasciencecentral.com/how-solid-pods-may-end-up-being-the-building-blocks-of-the-metaverse/
-  [x] Sergio
-  [x] Sonia
-  [x] Alejandro
-  [x] Nuria

**Comment by SergioArroni** [comment]
Que buen articulo !!
