### ISSUE TITLE
Como cliente quiero poder ver los detalles de un producto

### ISSUE THREAD

**Issue by UO232627** [Arquisoft/dede_es3c#135]
- [ ] FrontEnd
- [ ] BackEnd

**Comment by SergioArroni** [comment]
https://github.com/Arquisoft/dede_es3c/issues/119#issue-1164964272
Esta issue ya esta creada

**Comment by NuriaIF** [comment]
Me parece que son cosas diferentes, la issue anterior era ver el catálogo, esta es ver los detalles, entiendo que al seleccionar un producto concreto se puedan ver las especificaciones del mismo.

**Comment by SergioArroni** [comment]
A valep, perfect
