### ISSUE TITLE
Bloqueo en el Frontend

### ISSUE THREAD

**Issue by UO232627** [Arquisoft/dede_es3c#136]
Se ha encontrado un error a la hora de cargar los datos desde el backend:

"Invalid authorization: JsonWebTokenError: jwt malformed"

Estoy buscando la manera de solucionarlo.

**Comment by SergioArroni** [comment]
Es debido a que no has iniciado sesion en la aplicacion con un usuario registrado. Debes pasar el token que recibas en la peticion get por el header de esta peticion

**Comment by UO232627** [comment]
Solucionado
