### ISSUE TITLE
Calcular los precios con IVA

### ISSUE THREAD

**Issue by UO232627** [Arquisoft/dede_es3c#198]
Añadir al sistema que se calculen los precios con IVA. En la factura se pueden mostrar ambos precios, con y si IVA.

**Comment by NuriaIF** [comment]
Me parece bien mostrar los dos precios, antes de aplicar el IVA y después. El pedido puede guardar ambos.

**Comment by NuriaIF** [comment]
Cada producto ya viene con el IVA incluido. Lo que se suele hacer es mostrar en la factura el precio antes de aplicar el IVA y el precio total pagado.

Podríamos hacer eso, sería con el precio total del pedido restarle el IVA para mostrar precio total y precio sin IVA del pedido.
