### ISSUE TITLE
Tomar decisión de como tratar los pedidos para los que no hay stock suficiente

### ISSUE THREAD

**Issue by UO232627** [Arquisoft/dede_es3c#203]

**Comment by UO232627** [comment]
Algunos enlaces que pueden ser útiles

https://www.4webs.es/blog/gestionar-los-productos-sin-stock-las-tiendas-online
https://www.legalitas.com/actualidad/falta-stock-compras-online
https://www.labiznagadigital.es/blog/como-gestionar-productos-sin-stock-ecommerce/
https://www.labelium.com/blog/es/productos-sin-stock-ecommerce/

**Comment by SergioArroni** [comment]
Podríamos añadir un elemento en el carrito que sea un contador de elementos que puede comprar un usuario, el cual nunca pueda ser mayor que el stock que tenemos.

**Comment by UO232627** [comment]
Es una opción. Mostrariamos un mensaje de que no podría añadir más.

También habría que controlar que no pueda añadir un producto del que no hay 0 unidades. Habría que indicarlo también en el catálogo con un mensaje o destacando la card de alguna manera.

Cuando acabe con los test y la vista en detalle del producto investigaré a ver si se puede hacer facilmente.

**Comment by SoniaFernandezCoto** [comment]
Yo creo que la mejor opción es indicar en el catálogo cuando no hay stock y bloquear el botón de añadir al carrito si no hay stock del producto. De esta forma, nos ahorramos problemas de distribución.
