### ISSUE TITLE
Decidir qué queremos vender

### ISSUE THREAD

**Issue by NuriaIF** [Arquisoft/dede_es3c#24]

**Comment by SergioArroni** [comment]
Había pensado en una tienda de informática, con diferentes productos de ese sector

**Comment by NuriaIF** [comment]
Me parece buena idea

**Comment by SoniaFernandezCoto** [comment]
> Había pensado en una tienda de informática, con diferentes productos de ese sector

A mi me parece bien 😄

**Comment by UO232627** [comment]
> Había pensado en una tienda de informática, con diferentes productos de ese sector

Me parece bien!

**Comment by NuriaIF** [comment]
> > Había pensado en una tienda de informática, con diferentes productos de ese sector
> 
> Me parece bien.
> 
> Como alternativa podríamos hacer la tienda de mueble que habíamos comentado para poder reaprovechar los recursos del proyecto de IPS.

Es buena idea, podríamos tomar de ejemplo ese proyecto y hacer una tienda de muebles. Aunque al utilizar nuevas tecnologías no podríamos aprovechar mucho, sí que nos serviría para tener una idea más concreta de qué hacer y tomar como referencia algunas de las implementaciones.

Por otra parte, la tienda de informática tiene como ventaja que estamos familiarizados con los productos y tenemos experiencia comprando aparatos tecnológicos por Internet, lo que conseguirá que tengamos más entusiasmo por el proyecto durante el desarrollo porque nos gusta lo que estamos programando.

**Comment by UO232627** [comment]
> > > Había pensado en una tienda de informática, con diferentes productos de ese sector
> > 
> > 
> > Me parece bien.
> > Como alternativa podríamos hacer la tienda de mueble que habíamos comentado para poder reaprovechar los recursos del proyecto de IPS.
> 
> Es buena idea, podríamos tomar de ejemplo ese proyecto y hacer una tienda de muebles. Aunque al utilizar nuevas tecnologías no podríamos aprovechar mucho, sí que nos serviría para tener una idea más concreta de qué hacer y tomar como referencia algunas de las implementaciones.
> 
> Por otra parte, la tienda de informática tiene como ventaja que estamos familiarizados con los productos y tenemos experiencia comprando aparatos tecnológicos por Internet, lo que conseguirá que tengamos más entusiasmo por el proyecto durante el desarrollo porque nos gusta lo que estamos programando.

También es una buena opción. En mi opinión, ambas nos proporcionan opciones similares en cuanto al contenido de la aplicación y como distribuirlo o tratarlo internamente.

Esperemos a ver que dicen @SergioArroni y @SoniaFernandezCoto a ver que opinan.

**Comment by SoniaFernandezCoto** [comment]
La tienda de muebles habría estado bien si pudiésemos reutilizar el Script de la base de datos y seguir los prototipos anteriores. Pero en vista de que utilizmaos tecnologías diferentes y esta aplicación está orientada al público y la de muebles al personal de la tienda, creo que es más interesante utilizar productos informáticos para variar un poco.

**Comment by NuriaIF** [comment]
Finalmente, tras estar todos de acuerdo, haremos una tienda de informática.
