### ISSUE TITLE
Estudiar el trasvase de la base de datos de producción

### ISSUE THREAD

**Issue by UO232627** [Arquisoft/dede_es3c#244]
Hay que mirar si queremos mover la base de datos que tenemos desplegada en heroku en atlas.

Hugo nos ha comentado que tiene un repositorio que nos puede enseñar para guiarnos de como hacerlo.

**Comment by SergioArroni** [comment]
Tras estudiar las diferentes opciones se decidió dejarlo en 3 dockers claramente diferenciados como son Webapp, Backend y Database.
