### ISSUE TITLE
Tener varios centros de distribución

### ISSUE THREAD

**Issue by NuriaIF** [Arquisoft/dede_es3c#258]
El enunciado dice: "Añadir la posibilidad de que existan varios centros de distribución o almacenes en los que estén almacenados los productos."

Habría que plantearse varias cosas:

- Que se calcule automáticamente el centro de distribución más cercano a la dirección del cliente, y ese será desde dónde se envíen los productos

- Elegir entre 1 y 2:
1. Si algún producto del pedido no está disponible en el centro de distribución más cercano, hay que decidir si:

           a. Enviar el pedido desde 2 (o más) centros de distribución, aplicándole al cliente el incremento del precio del más lejano
           b. Enviar desde el centro de distribución más cercano de los que tengan todos los productos del pedido disponibles
                - En este caso, si el pedido no puede completarse con un solo centro de distribución, ¿hacer lo expuesto en el apartado a?

2. Enviar siempre desde el centro de distribución más cercano, asegurando un mínimo de stock en todos ellos, y si no se enviará desde un centro de distribución a otro para "reponer". En este caso el precio del envío sería según la distancia al más cercano, puesto que es este el que distribuye el pedido entero al cliente.

**Comment by NuriaIF** [comment]
Otra opción, quizá más fácil, sería dejar un solo centro de distribución pero tener distintos almacenes
De los almacenes viajaría al centro de distribución
Entonces, a la hora de hacer un pedido, se calcula la distancia a ese único centro de distribución y ya se forma el pedido cogiendo de los almacenes necesarios

**Comment by SergioArroni** [comment]
Yo añadiría una tercera opción que fuera, si no tenemos stock en el almacén que pide el usuario no dejarle hacer el pedido a ese centro de distribución. A la hora de elegir cual de los puede escoger, solo habilitar el que tenga stock, algo parecido a lo que hace aliexpress. Limitamos la cantidad de productos pedibles por el usuario a la cantidad máxima de stock de un centro de distribución. Si uno tiene 4 y otro 2, el usuario solo podría pedir hasta 4 elementos de ese producto y si se extiende de 2, solo podría pedirlos al primero.

**Comment by NuriaIF** [comment]
Me gusta esta tercera opción, que el propio usuario elija el centro de distribución pero yo añadiría que lo haga por cada producto. Y podemos modificarlo para que el pedido no tenga precio de envío, sino que ahora haya un precio de envío por cada producto del pedido.

**Comment by NuriaIF** [comment]
Finalmente, nos hemos decantado por esta opción:

> Yo añadiría una tercera opción que fuera, si no tenemos stock en el almacén que pide el usuario no dejarle hacer el pedido a ese centro de distribución. A la hora de elegir cual de los puede escoger, solo habilitar el que tenga stock, algo parecido a lo que hace aliexpress. Limitamos la cantidad de productos pedibles por el usuario a la cantidad máxima de stock de un centro de distribución. Si uno tiene 4 y otro 2, el usuario solo podría pedir hasta 4 elementos de ese producto y si se extiende de 2, solo podría pedirlos al primero.

Con la aclaración de que la elección de cada centro de distribución se hace por producto y no por pedido, similar a AliExpress.
