### ISSUE TITLE
Trabajo hecho por cada integrante del equipo para la primera entrega de la documentación

### ISSUE THREAD

**Issue by UO232627** [Arquisoft/dede_es3c#28]
Que cada uno escriba lo que ha hecho durante esta primera entrega para que los demas lo validen.

**Comment by UO232627** [comment]
Apartados de la documentación:

     2. Architecture constraints
     5.1. Building block view - Level 1
     6. Runtime View - Diagramas 6.7, 6.8 y 6.9
     8. Concepts - Apartados 8.4 a 8.9
     9. Design decisions
     12. Glosary

**Comment by NuriaIF** [comment]
Apartados de la documentación realizados:

    1. Introduction and goals
    6. Runtime View - Diagramas 6.3 y 6.4
    8.1 Concepts - Domain model
    11. Risks and technical debts
    12. Glossary

**Comment by SoniaFernandezCoto** [comment]
Apartados de la documentacion realizados:
3.1. Business Context
6. Runtime view - Diagramas 6.5 y 6.6
8.3. User Interface
10. Quality Scenarios
12. Glossary (algunos términos)
