### ISSUE TITLE
Decidir si usar MongoDB o SQLite para la BD del proyecto

### ISSUE THREAD

**Issue by SergioArroni** [Arquisoft/dede_es3c#3]
#1 Debate BD
NoSQL->MongoDB - recomendado por la asiganatura y se usara en otras asignaturas.
SQL->SQLite - estamos más familiarizados con él.
Buscar más argumentos para usar cada uno de ellos y decidir cual usaremos.

**Comment by UO232627** [comment]
Voy a plantear las ventajas y desventajas que veo a ambas opciones:

# MongoDB
## Ventajas
- Es recomendación de los profesores.
- Más adelante se usará en la asignatura SDI, por lo que nos podría venir bien tener un primer contacto con ella.
- Es la primera toma de contacto con una base no relacional, por lo que estaría bien aprender a usarlas.

## Desventajas
- Al ser una tecnología nueva, el flujo de trabajo puede verse ralentizado al tener que aprenderla.
- Usar una base de datos no relacional para una aplicación "pequeña" puede ser un poco excesivo.

# SQLite
## Ventajas
- Al ser una base de datos relacional es una tecnología conocida y con la que nos sabemos manejar.

## Desventajas
- REACT y TypeScrypt son nuevas para nosotros, por lo que no se si la integración con nuestro sistema será la correcta.

**Comment by SergioArroni** [comment]
Yo usaría MongoDB, ya que es una BD NoSQL la cual nos vendría bien para los productos, ya que no sabemos que atributos pueden tener o si habrá un nuevo producto con más atributos.
