### ISSUE TITLE
Como cliente quiero seleccionar el centro de distribución por cada producto

### ISSUE THREAD

**Issue by NuriaIF** [Arquisoft/dede_es3c#312]
Al hacer el pedido, seleccionar el centro de distribución.
Basado en AliExpress, donde por cada producto se selecciona el centro de distribución:

![carrito](https://user-images.githubusercontent.com/79658237/166009089-9e80339e-8e2d-4a17-8303-ee2e4f8c30f3.png)

**Comment by SoniaFernandezCoto** [comment]
Hecho!
