### ISSUE TITLE
Curso sobre FrontEnd y BackEnd

### ISSUE THREAD

**Issue by NuriaIF** [Arquisoft/dede_es3c#41]
Curso para crear aplicaciones de una sola página con ReactJS que utilizan API REST creadas con Node.js
[Bootcamp Fullstack](https://fullstackopen.com/es/)

- [x] Alejandro
- [x] Nuria
- [x] Sergio
- [x] Sonia

**Comment by SergioArroni** [comment]
Muy bueno
