### ISSUE TITLE
Dividir el 6.2 

### ISSUE THREAD

**Issue by SergioArroni** [Arquisoft/dede_es3c#58]

**Comment by UO232627** [comment]
El cambio es hacer que cuando se haga login en la app, no se haga simultaneamente en la base de datos y el pod, sino que solo se haga en la base de datos y el login del pod solo see haga cuando se necesite (por ejemplo cuando se vaya a pagar y necesite acceso a esos datos)

**Comment by SergioArroni** [comment]
https://github.com/Arquisoft/dede_es3c/pull/95#issue-1160363130
