### ISSUE TITLE
Trabajar en ramas independientes

### ISSUE THREAD

**Issue by UO232627** [Arquisoft/dede_es3c#62]
Como vamos a trabajar con historias de usuario y casos de uso, crearemos una rama para cada uno de ellos. Estas ramas deberian de crearse dentro de la rama propia de cada uno para tener bien identificado el trabajo realizado.

**Comment by NuriaIF** [comment]
Como habíamos decidido, se está realizando el trabajo en ramas. Estamos llamando a las ramas con el nombre del miembro del equipo que la hace seguido de algo más específico, por ejemplo una palabra que describa lo que se vaya a desarrollar en esa rama. 

Ejemplo:
- "Nuria_Pedidos" para los casos de uso relacionados con los pedidos en el BackEnd.

**Comment by SergioArroni** [comment]
Se trabajo en ramas separadas
