### ISSUE TITLE
Nomenclatura internacionalización 

### ISSUE THREAD

**Issue by SergioArroni** [Arquisoft/dede_es3c#63]

**Comment by SergioArroni** [comment]
Hacemos dos idiomas, ingles y español y divinos en dos ficheros con todas las etiquetas que puedan cambiar ?

**Comment by UO232627** [comment]
Me parece bien la idea de @SergioArroni

**Comment by NuriaIF** [comment]
Estoy de acuerdo

**Comment by SoniaFernandezCoto** [comment]
En los ficheros se puede identificar cada elemento como "nombrepagina.nombreElemento"
