### ISSUE TITLE
Arquitectura hexagonal 😏 

### ISSUE THREAD

**Issue by NuriaIF** [Arquisoft/dede_es3c#69]
Vamos a utilizar una arquitectura hexagonal en la persistencia

**Comment by NuriaIF** [comment]
Hemos tomado esta decisión porque cuando empezamos con la BD estábamos debatiendo entre SQLite y MongoDB, y esta opción permitía las 2 😄

**Comment by SergioArroni** [comment]
Esta añadido correctamente
