### ISSUE TITLE
Decidir entidades

### ISSUE THREAD

**Issue by NuriaIF** [Arquisoft/dede_es3c#71]
Hay que decidir las entidades

**Comment by SoniaFernandezCoto** [comment]
Mínimo de cara a establecer los casos de uso, deberíamos incluir clientes y la perspectiva de administrador que habíamos hablado de implementar

**Comment by SergioArroni** [comment]
Desde un punto de vista del backend añadiría Products, pero no creo que tengan en si casos de uso

**Comment by UO232627** [comment]
De cara a simular el envío de productos podríamos incluir la empresa de envíos como una entidad aunque no tenga mucha funcionalidad dentro de nuestra app. Podríamos considerarla simplemente como una entidad receptora de la información de envío.

**Comment by NuriaIF** [comment]
> De cara a simular el envío de productos podríamos incluir la empresa de envíos como una entidad aunque no tenga mucha funcionalidad dentro de nuestra app. Podríamos considerarla simplemente como una entidad receptora de la información de envío.

La empresa de envíos no sería una entidad, nosotros simulamos la compra, no nos metemos en la parte del envío.

**Comment by NuriaIF** [comment]
> Desde un punto de vista del backend añadiría Products, pero no creo que tengan en si casos de uso

Como entidad en el BackEnd también habría que añadir Orders, pero no estoy segura de si nos estamos confundiendo. Creo que una cosa son entidades para los casos de uso (que serían cliente y admin) y luego entidades en el BackEnd son diferentes y van a parte.

**Comment by SergioArroni** [comment]
> > Desde un punto de vista del backend añadiría Products, pero no creo que tengan en si casos de uso
> 
> Como entidad en el BackEnd también habría que añadir Orders, pero no estoy segura de si nos estamos confundiendo. Creo que una cosa son entidades para los casos de uso (que serían cliente y admin) y luego entidades en el BackEnd son diferentes y van a parte.

Estoy de acuerdo contigo, son dos conceptos diferentes

**Comment by NuriaIF** [comment]
Yo diría que las entidades son "cliente" y "administrador", y quizá también "usuario" para los casos donde se englobe tanto a cliente como al admin. ¿O sería mejor hacer 2 casos de uso diferentes, aunque la funcionalidad sea la misma?

**Comment by SergioArroni** [comment]
Yo diría que es Cliente y Administrador, diferenciados

**Comment by NuriaIF** [comment]
Perfecto, entonces tenemos 2 entidades para los casos de uso 😄
