### ISSUE TITLE
Juntar Heroku con MongoDB

### ISSUE THREAD

**Issue by SergioArroni** [Arquisoft/dede_es3c#77]

**Comment by NuriaIF** [comment]
Se supone que ya está juntado, pero falla el despliegue de la aplicación en Heroku. El despliegue se ha pospuesto para la tercera entrega, por lo que cuando se despliegue la aplicación en Heroku verificaremos que se ha conectado correctamente con MogoDB. Por lo tanto, procedemos a posponer la comprobación de si realmente está conectado para la tercera entrega.

Issue donde se explica el problema que estamos teniendo al intentar desplegar en Heroku:
[Problema para desplegar la app en Heroku](https://github.com/Arquisoft/dede_es3c/issues/99#issue-1160743141)

**Comment by SergioArroni** [comment]
Ya esta juntado pero con AWS en vez de con Heroku
