### ISSUE TITLE
Buscar estandar POD

### ISSUE THREAD

**Issue by UO232627** [Arquisoft/dede_es3c#82]
Buscar información sobre que estándares podemos sobre que información de usuario podemos o no guardar.

**Comment by SergioArroni** [comment]
Podemos añadir:
{
'personal_identification' : 'dni/pasaporte',
'name' : 'Sergio Arroni del Riego',
'password' : '*****',
'location' : [ 
{
'Pais: España,
 Provincia: Asturias, 
Ciudad: Gijón,
 Calle: X,
 Nº: X,
 Piso: X'
}
]
}
o 
Separarlo por los datos de la ubicacion, como lo veis?

**Comment by NuriaIF** [comment]
Lo veo bastante bien, podemos comentarlo por el issue del repositorio faq 😄

**Comment by NuriaIF** [comment]
[Propuesta en la faq](https://github.com/Arquisoft/faq/issues/29#issuecomment-1058980087)

**Comment by NuriaIF** [comment]
Aún sin llegar a un acuerdo, pospuesto para la tercera entrega. A ver si antes de la tercera entrega se consigue un acuerdo para utilizar un mismo estándar.

**Comment by SoniaFernandezCoto** [comment]
Hemos decidido utilizar los campos del POD de Labra mientras no se llegue a ningún acuerdo
