### ISSUE TITLE
Juntar los Docker con Heroku 

### ISSUE THREAD

**Issue by SergioArroni** [Arquisoft/dede_es3c#89]

**Comment by NuriaIF** [comment]
Como aún no hemos conseguido desplegar la app en Heroku, posponemos juntar los Docker con Heroku para la tercera entrega.

En este issue se expone el problema que estamos teniendo: [Problemas para desplegar la app en Heroku](https://github.com/Arquisoft/dede_es3c/issues/99#issue-1160743141)

**Comment by NuriaIF** [comment]
Estamos en ello

**Comment by SergioArroni** [comment]
Ya esta juntado pero con AWS en vez que con Heroku
