### ISSUE TITLE
Problemas para desplegar la app en heroku 😭 

### ISSUE THREAD

**Issue by NuriaIF** [Arquisoft/dede_es3c#99]
Estoy teniendo problemas para desplegar la aplicación en heroku. Lo estoy probando en un fork del repositorio para no liarla ya que tiene que ir al master. Me da un error con el módulo "eslint".

**Comment by NuriaIF** [comment]
Debido a que no urge para esta entrega, hemos decidido posponerlo para la tercera.

**Comment by NuriaIF** [comment]
Debido a varios problemas que nos han surgido intentando desplegar nos vemos en la necesidad de posponerlo para la cuarta entrega

**Comment by SergioArroni** [comment]
En la cuarta entrega al final decidimos desplegarlo en AWS
